version: 2
jobs:
  build-test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  docker-build:
    environment:
      IMAGE_NAME: ashwathisshiva/messagemanager
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg version=1.0.0 -t $IMAGE_NAME:${CIRCLE_SHA1} .
            docker tag $IMAGE_NAME:${CIRCLE_SHA1} $IMAGE_NAME:latest
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:${CIRCLE_SHA1}
            docker push $IMAGE_NAME:latest
            docker logout

workflows:
  version: 2
  build-and-push-messagemanager:
    jobs:
      - build-test:
          filters:
            branches:
              only: master
      - docker-build:
          requires:
            - build-test
          filters:
            branches:
              only: master
